http://127.0.0.1:3000/getcocktails
################################
http://127.0.0.1:3000/cocktails/Alice/zutaten
################################
http://127.0.0.1:3000/cocktails/7.2
################################